spring:
  application:
    name: j-booking


  web:
    resources:
      add-mappings: false

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

  datasource:
    url: jdbc:postgresql://localhost:5432/j_booking
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# бизнес-параметры бронирования
booking:
  min-nights: 1
  main-guest-count: 1
  cancellation:
    full-refund-hours: 72
    partial-refund-hours: 24
    full-refund-percent: 100
    partial-refund-percent: 50
    no-refund-percent: 0

# параметры валидации
validation:
  min-stars: 1
  max-stars: 5
  min-rating: 1
  max-rating: 5
  min-guests: 1

client:
  payment:
    url: http://localhost:9090
